# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9488f21112ad850eb4edb18851624bc53d26891ec9c8daf61239c525d93087cecf4aeffc7df49afce0e0703f9568685f20b9cf5b2fb15f247b8f71633bcfd3e

test:
  secret_key_base: a261455212d2510e423bfab0b1b5d0033917ccb0081594e1eb603c4dc6422852e414d5034b0a696fedcb9ad8f371874db46d66533f9d9e9356534d095d489a37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
